[dotup,setup] updates to setup scripts with more friendly interaction

diff --git a/bin/_dotup b/bin/_dotup
--- a/bin/_dotup
+++ b/bin/_dotup
@@ -15,9 +15,37 @@ echo '
 ==================================================================================
 '
 
+# -- REFs
 # neat things for echo'ing colors
   # https://github.com/ctaylo21/jarvis/blob/master/install.sh#L3
   # $(tput setaf 2)JARVIS: Greetings. Preparing to power up and begin diagnostics.$(tput sgr 0)
+
+
+set -e
+
+
+trap 'clean_exit $? $LINENO' EXIT
+
+
+function log {
+  printf '[%s] %s\n' "$(date '+%x %X')" "$*"
+}
+
+function clean_exit {
+  set +x
+  if [[ "$1" != "0" ]]; then
+    log "Fatal error code \"${1}\" occurred on line \"${2}\""
+  fi
+}
+
+
+log "Some setup methods require the administrator password. Please grant sudo access:"
+sudo -v
+
+
+# Keep-alive: update existing `sudo` time stamp until setup has finished
+while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
+
 
 # Detect OS
 if [[ -z $PLATFORM ]]
@@ -95,9 +123,6 @@ else
     cd $HOME
   fi
 fi
-
-# Get permissions (super powers) up front and only once
-sudo -v
 
 # Install Homebrew
 if (which brew &>/dev/null); then
