wip fixes

diff --git a/bin/brew-install b/bin/brew-install
--- a/bin/brew-install
+++ b/bin/brew-install
@@ -19,18 +19,35 @@ __root="$(cd "$(dirname "${__dir}")" && pwd)"
 # shellcheck disable=SC2034,SC2015
 __invocation="$(printf %q "${__file}")$( (($#)) && printf ' %q' "$@" || true)"
 
-paq_path="${XDG_DATA_HOME}/nvim/site/pack/paqs/start/paq-nvim"
+FORCE_INSTALL="false"
+
+while getopts "f" OPTION; do
+  case $OPTION in
+
+    f)
+      FORCE_INSTALL="true"
+      ;;
+
+    \?)
+      echo "Invalid Option: -$OPTARG" 1>&2
+      exit 1
+      ;;
+
+  esac
+done
+shift $((OPTIND - 1))
 
 do_install() {
-  log "cloning paq-nvim into $paq_path"
-  git clone --depth=1 https://github.com/savq/paq-nvim.git $paq_path \
-    && nvim -c 'lua require("paq")(require("plugins").list):install()' +qall \
-    && log_ok "completed installing paq-nvim and plugins into $paq_path" \
+  log "installing brew"
+  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" \
+    && log_ok "completed installing brew" \
     || exit 1
 }
 
-if [[ ! -d $paq_path ]]; then
-  read -p "$(tput bold)$(tput setaf 5)[?] install paq-nvim and plugins (Y/n)?$(tput sgr 0) " yn
+if [[ $(type "brew" &>/dev/null) && $FORCE_INSTALL == "false" ]]; then
+  log_warn "brew already installed; skipping."
+else
+  read -p "$(tput bold)$(tput setaf 5)[?] install brew (Y/n)?$(tput sgr 0) " yn
   case $yn in
     [Yy]*)
       do_install || exit 1
@@ -39,13 +56,11 @@ if [[ ! -d $paq_path ]]; then
       do_install || exit 1
       ;;
     [Nn]*)
-      log_warn "opted out of paq-nvim install"
+      log_warn "opted out of brew install"
       ;;
     *)
       log_warn "please answer [y]es or [n]o."
       exec $__invocation
       ;;
   esac
-else
-  log_warn "paq-nvim already exists at $paq_path; skipping."
 fi
diff --git a/bin/nvim-install b/bin/nvim-install
--- a/bin/nvim-install
+++ b/bin/nvim-install
@@ -1,6 +1,13 @@
 #!/bin/bash
 
-[[ -f "$XDG_CONFIG_HOME/zsh/lib/helpers.zsh" ]] && source "$XDG_CONFIG_HOME/zsh/lib/helpers.zsh"
+if [[ -z $XDG_DATA_HOME ]]; then
+  export XDG_DATA_HOME="$HOME/.local/share"
+fi
+if [[ -z $XDG_CONFIG_HOME ]]; then
+  export XDG_CONFIG_HOME="$HOME/.config"
+fi
+
+[[ -f "${XDG_CONFIG_HOME}/zsh/lib/helpers.zsh" ]] && source "${XDG_CONFIG_HOME}/zsh/lib/helpers.zsh"
 
 set -euo pipefail
 
@@ -14,67 +21,67 @@ __invocation="$(printf %q "${__file}")$( (($#)) && printf ' %q' "$@" || true)"
 
 FORCE_INSTALL="false"
 
-pushd "$XDG_DATA_HOME/src" >/dev/null && log_ok "cd ~/.local/share/src successful"
+pushd "${XDG_DATA_HOME}/src" >/dev/null && log_ok "cd ~/.local/share/src successful"
 
 update() {
-	cd "$XDG_DATA_HOME/src/neovim" && log_ok "cd neovim successful"
-	git checkout master && log_ok "git checkout master successful"
-	git fetch && log_ok "git fetch successful"
-	git log --color --pretty=oneline --abbrev-commit HEAD@{1}.. | sed 's/^/  /'
+  cd "${XDG_DATA_HOME}/src/neovim" && log_ok "cd neovim successful"
+  git checkout master && log_ok "git checkout master successful"
+  git fetch && log_ok "git fetch successful"
+  git log --color --pretty=oneline --abbrev-commit HEAD@{1}.. | sed 's/^/  /'
 }
 
 clone() {
-	if [[ ! -d "$XDG_DATA_HOME/src/neovim" ]]; then
-		git clone git@github.com:neovim/neovim.git && log_ok "git clone neovim successful"
-		cd neovim && log_ok "cd neovim successful"
-		# do it all and then exit cleanly...
-		update && build && popd >/dev/null && exit 0
-	fi
+  if [[ ! -d "${XDG_DATA_HOME}/src/neovim" ]]; then
+    git clone git@github.com:neovim/neovim.git && log_ok "git clone neovim successful"
+    cd neovim && log_ok "cd neovim successful"
+    # do it all and then exit cleanly...
+    update && build && popd >/dev/null && exit 0
+  fi
 }
 
 do_build() {
-	git up && log_ok "git up successful"
-	[[ -d "$XDG_DATA_HOME/src/neovim/.deps" ]] && sudo rm -rf "$XDG_DATA_HOME/src/neovim/.deps" && log_ok "remove .deps successful" || exit 1
-	sudo make CMAKE_BUILD_TYPE=RelWithDebInfo || exit 1 && log_ok "make successful"
-	sudo make install || exit 1 && log_ok "successfully built and installed neovim"
+  git up && log_ok "git up successful"
+  [[ -d "${XDG_DATA_HOME}/src/neovim/.deps" ]] && sudo rm -rf "${XDG_DATA_HOME}/src/neovim/.deps" && log_ok "remove .deps successful" || exit 1
+  sudo make CMAKE_BUILD_TYPE=RelWithDebInfo || exit 1 && log_ok "make successful"
+  sudo make install || exit 1 && log_ok "successfully built and installed neovim"
 }
 
 build() {
-	if [[ $(git rev-parse HEAD) == $(git rev-parse @{u}) && $FORCE_INSTALL == "false" ]]; then
-		log_warn "neovim already up to date on origin/master; skipping."
-	else
-		read -p "$(tput bold)$(tput setaf 5)[?] build neovim from source (Y/n)?$(tput sgr 0) " yn
-		case $yn in
-			[Yy]*)
-				do_build || exit 1
-				;;
-			"")
-				do_build || exit 1 # default
-				;;
-			[Nn]*)
-				log_warn "opted out of neovim install"
-				;;
-			*)
-				log_warn "please answer [y]es or [n]o."
-				exec $__invocation
-				;;
-		esac
-	fi
+  if [[ $(git rev-parse HEAD) == $(git rev-parse @{u}) && $FORCE_INSTALL == "false" ]]; then
+    log_warn "neovim already up to date on origin/master; skipping."
+  else
+    read -p "$(tput bold)$(tput setaf 5)[?] build neovim from source (Y/n)?$(tput sgr 0) " yn
+    case $yn in
+      [Yy]*)
+        do_build || exit 1
+        ;;
+      "")
+        do_build || exit 1 # default
+        ;;
+      [Nn]*)
+        log_warn "opted out of neovim install"
+        ;;
+      *)
+        log_warn "please answer [y]es or [n]o."
+        exec $__invocation
+        ;;
+    esac
+  fi
 }
 
 while getopts "f" OPTION; do
-	case $OPTION in
+  case $OPTION in
 
-		f)
-			FORCE_INSTALL="true"
-			;;
+    f)
+      FORCE_INSTALL="true"
+      ;;
 
-		\?)
-			echo "Invalid Option: -$OPTARG" 1>&2
-			exit 1
-			;;
+    \?)
+      echo "Invalid Option: -$OPTARG" 1>&2
+      exit 1
+      ;;
 
-	esac
+  esac
 done
 shift $((OPTIND - 1))
 
