feat: use calm-notifications dnd rb file directly

diff --git a/bin/dnd b/bin/dnd
--- a/bin/dnd
+++ b/bin/dnd
@@ -14,50 +14,50 @@ set -euo pipefail
 command=""
 subcommand=""
 
-if ! which calm-notifications &>/dev/null; then
-	printf "$(tput setaf 1)✖ %s$(tput sgr0)\n" 'unable to run dnd; it requires `brew install "vitorgalvao/tiny-scripts/calm-notifications"`'
-	return 1
-fi
+# if ! which dnd.rb &>/dev/null; then
+#   printf "$(tput setaf 1)✖ %s$(tput sgr0)\n" 'unable to run dnd; it requires `brew install "vitorgalvao/tiny-scripts/calm-notifications"`'
+#   return 1
+# fi
 
 command="$(basename "$0")"
 
 help() {
-	printf -- "Usage: "$command" <subcommand> [options]\n"
-	printf -- "Subcommands:\n"
-	printf -- "    on       Turn ON do-not-disturb (DND) mode\n"
-	printf -- "    off      Turn OFF do-not-disturb (DND) mode\n"
-	printf -- "    toggle   Toggle do-not-disturb (DND) mode ON and OFF\n"
-	printf -- "    status   Get the current status of do-not-disturb (DND) mode\n"
+  printf -- "Usage: "$command" <subcommand> [options]\n"
+  printf -- "Subcommands:\n"
+  printf -- "    on       Turn ON do-not-disturb (DND) mode\n"
+  printf -- "    off      Turn OFF do-not-disturb (DND) mode\n"
+  printf -- "    toggle   Toggle do-not-disturb (DND) mode ON and OFF\n"
+  printf -- "    status   Get the current status of do-not-disturb (DND) mode\n"
 }
 
 on() {
-	calm-notifications on
+  dnd.rb on
 }
 
 off() {
-	calm-notifications off
+  dnd.rb off
 }
 
 toggle() {
-	calm-notifications toggle
+  dnd.rb toggle
 
-	status
+  status
 }
 
 status() {
-	echo "$(calm-notifications status)"
+  echo "$(dnd.rb status)"
 }
 
-subcommand=$1
+subcommand="${1:-}"
 case $subcommand in
-	'')
-		toggle
-		;;
-	'-h' | '--help')
-		help
-		;;
-	*)
-		shift
-		${subcommand} $@
-		;;
+  '')
+    toggle
+    ;;
+  '-h' | '--help')
+    help
+    ;;
+  *)
+    shift
+    ${subcommand} $@
+    ;;
 esac
