fix(duc): finally works! abduco with fzf

diff --git a/bin/duc b/bin/duc
--- a/bin/duc
+++ b/bin/duc
@@ -1,5 +1,9 @@
 #!/usr/bin/env bash
 
+# REF:
+# - https://github.com/oliverralbertini/shell_functions/blob/249fea2d9e7679e80d762ab921a403f6cc6acbb6/abduce.sh
+# - https://github.com/DoomHammer/tmux-scratch/blob/a935ec522733dfd6c8d0535995054d62e73ad37f/scripts/scratch.sh
+
 set -euo pipefail
 
 [[ -f "$ZDOTDIR/lib/helpers.zsh" ]] && source "$ZDOTDIR/lib/helpers.zsh"
@@ -13,7 +17,8 @@ function __help() {
   printf -- "\n"
   printf -- "Options:\n"
   printf -- "  -h  This help text you're presently reading 😄\n"
-  printf -- "  -a  Immediately attach to the created session\n"
+  printf -- "  -b  Background the newly created session\n"
+  printf -- "  -l  List abduco sessions non-interactively\n"
   printf -- "\n"
   printf -- "Examples:\n"
   printf -- "  duc processes htop\n"
@@ -29,7 +34,7 @@ function __help() {
 
 IMMEDIATELY_ATTACH="true"
 
-while getopts "hb" OPTION; do
+while getopts "hbl" OPTION; do
   case $OPTION in
     b)
       IMMEDIATELY_ATTACH="false"
@@ -39,10 +44,15 @@ while getopts "hb" OPTION; do
       __help
       ;;
 
+    l)
+      abduco -l
+      exit 0
+      ;;
+
     \?)
       # NOTE: this covers the case where an optarg may not be provided
       # and will exit errored
-      echo "Invalid Option: -$OPTARG" 1>&2
+      log_error "Invalid Option: -$OPTARG" 1>&2
       exit 1
       ;;
   esac
@@ -53,7 +63,7 @@ shift "$((OPTIND - 1))"
 session_name="${1:-}"
 shift
 
-cmd="${*:-}"
+cmd="${@:-}"
 
 # -- try to change to an existing session; otherwise, create a new one
 function try_session() {
@@ -70,25 +80,30 @@ function try_session() {
   fi
 
   if abduco -l | grep -q "$session"; then
-    echo "session $session exists"
-    abduco -a "$session"
+    log_info "attaching to session $session..."
+    sleep 0.3
+    abduco -A "$session"
   elif [[ -n "$cmd" ]]; then
-    # FIXME: why is this not working? `$cmd` isn't running :sadpanda:
-    echo "session $session DOES NOT exist; creating with command $cmd.."
-    command abduco "$session_create_opt" "$session" "$cmd"
+    log_warn "creating session $session; with command $cmd..."
+    sleep 0.3
+    echo "${cmd[@]}" | xargs abduco "$session_create_opt" "$session"
   else
-    echo "could not attach to or create new session named $session; exiting.."
+    log_error "could not attach to or create new session named $session; exiting.."
     exit 1
   fi
-
-  exit 0
 }
 
 function fuzzy_find() {
   # -- prepare for fuzzy-finding!!
   # REF: finds the attached session abduco -l | awk '$1 ~ /^\*/'
-  sessions_list=$(abduco | tail -n+2 | cut -f 4)
-  # sessions_count=$(echo "$sessions_list" | wc -l | sed -e 's/^[[:space:]]*//')
+  # sessions_list=$(abduco | tail -n+2 | cut -f 4)
+  sessions_list=$(abduco | tail -n +2 | awk '{print $NF}')
+
+  if [[ -z "$sessions_list" ]]; then
+    printf -- "${yellow}No %s${reset}\n" "$(abduco)"
+    printf -- "\n"
+    __help
+  fi
 
   fzf_prompt_text=" attach to session  "
 
