wip: uncommitted changes

diff --git a/bin/ftm b/bin/ftm
--- a/bin/ftm
+++ b/bin/ftm
@@ -71,30 +71,30 @@ fi
 while getopts "phs:" OPTION; do
   case $OPTION in
 
-  p)
-    export TMUX_POPUP=1
-    POPUP="true"
-    ;;
+    p)
+      export TMUX_POPUP=1
+      POPUP="true"
+      ;;
 
-  h)
-    __help
-    ;;
-  s)
-    SAVED_SESSION_NAME="$OPTARG"
-    echo "Saving session with session name: $OPTARG"
-    exit 0
-    ;;
+    h)
+      __help
+      ;;
+    s)
+      SAVED_SESSION_NAME="$OPTARG"
+      echo "Saving session with session name: $OPTARG"
+      exit 0
+      ;;
 
-  \?)
-    # NOTE: this covers the case where an optarg may not be provided
-    # and will exit errored
-    echo "Invalid Option: -$OPTARG" 1>&2
-    exit 1
-    ;;
-  :)
-    echo "Invalid Option: -$OPTARG requires an argument" 1>&2
-    exit 1
-    ;;
+    \?)
+      # NOTE: this covers the case where an optarg may not be provided
+      # and will exit errored
+      echo "Invalid Option: -$OPTARG" 1>&2
+      exit 1
+      ;;
+    :)
+      echo "Invalid Option: -$OPTARG requires an argument" 1>&2
+      exit 1
+      ;;
   esac
 done
 # shift $((OPTIND - 1))
@@ -211,7 +211,7 @@ function fuzzy_find() {
 
   # -- do certain things based upon only one active session
   if [[ $sessions_count == 1 ]]; then
-    fzf_prompt_text=" create new session  "
+    fzf_prompt_text=" create new session  "
     fzf_header_text=""
 
     # -- provide user with their available pre-defined layouts (assumes certain dir)
@@ -220,7 +220,7 @@ function fuzzy_find() {
     [[ $layouts_sessions_count -gt 0 ]] && fzf_header_text="${header_icon} possible layouts"
     [[ $layouts_sessions_count -gt 0 ]] && preview_cmd="fd {} $layouts_dir | xargs bat"
   else
-    fzf_prompt_text=" new or existing session  "
+    fzf_prompt_text=" new or existing session  "
     fzf_header_text="${header_icon} $(tput sitm)$(tput setaf 5)$current_session$(tput sgr 0) [$(tput setaf 255)ctrl-p$(tput sgr 0): $(tput setaf 245)pinvim / $(tput setaf 255)ctrl-x$(tput sgr 0): $(tput setaf 245)kill / $(tput setaf 255)ctrl-r$(tput sgr 0): $(tput setaf 245)rename$(tput sgr 0)]"
   fi
 
