dump()

diff --git a/bin/git-wt b/bin/git-wt
--- a/bin/git-wt
+++ b/bin/git-wt
@@ -11,8 +11,8 @@ set -euo pipefail
 
 source "$HOME/.config/zsh/lib/helpers.zsh"
 
-input_args=${*:-}
-args=("$input_args")
+# input_args=${*:-}
+# args=("$input_args")
 
 (command -v fzf &>/dev/null) && FZF_FOUND="installed" || FZF_FOUND="not installed"
 
@@ -26,10 +26,13 @@ __invocation="$(printf %q "$__file")$( (($#)) && printf ' %q' "$@" || true)"
 
 # -- friendly help if -h option given
 function __help() {
-  printf -- "Usage: %s [options] [SESSION_NAME | FUZZY_PATTERN]\n" "$__base"
+  printf -- "Usage: %s [commands] [WORKTREE | FUZZY_PATTERN]\n" "$__base"
   printf -- "\n"
-  printf -- "   Options:\n"
-  printf -- "     -h              This help text you're presently reading. 😄\n"
+  printf -- "   Commands:\n"
+  printf -- "     list              List checked out worktrees. \n"
+  printf -- "     list -b           List remote branches/worktrees. \n"
+  printf -- "     -                 Check out Main worktree. \n"
+  printf -- "     help              This help text you're presently reading. 😄\n"
   printf -- "\n"
   printf -- "   Dependencies:\n"
   printf -- "     fzf             (%s)\n" "$FZF_FOUND"
@@ -50,47 +53,72 @@ function __change_worktree() {
   fi
 }
 
-while getopts "h" OPTION; do
-  case $OPTION in
-    h)
-      __help
-      ;;
-
-    \?)
-      # NOTE: this covers the case where an optarg may not be provided
-      # and will exit errored
-      echo "Invalid Option: -$OPTARG" 1>&2
-      exit 1
-      ;;
-
-    :)
-      echo "Invalid Option: -$OPTARG requires an argument" 1>&2
-      exit 1
-      ;;
-  esac
-done
-# shift $((OPTIND - 1))
-shift "$(($OPTIND - 1))"
+# while getopts "h" OPTION; do
+#   case $OPTION in
+#     h)
+#       __help
+#       ;;
+#
+#     \?)
+#       # NOTE: this covers the case where an optarg may not be provided
+#       # and will exit errored
+#       echo "Invalid Option: -$OPTARG" 1>&2
+#       exit 1
+#       ;;
+#
+#     :)
+#       echo "Invalid Option: -$OPTARG requires an argument" 1>&2
+#       exit 1
+#       ;;
+#   esac
+# done
+# # shift $((OPTIND - 1))
+# shift "$(($OPTIND - 1))"
 
 # -- this is our given session_name param, sans options
-# worktree="${1:-}"
+worktree="${1:-}"
 directory=""
 
-# case "$worktree" in
-#   list)
-#     git worktree list
-#     ;;
-#   -)
-#     directory=$(git worktree list --porcelain | grep -E 'worktree ' | awk '{print $0; exit}' | cut -d ' ' -f2-)
-#     ;;
-#   *)
-#     directory=$(git worktree list --porcelain | grep -E 'worktree ' | awk '/'"$worktree"'/ {print; exit}' | cut -d ' ' -f2- | fzf)
-#     ;;
-# esac
-
+case "$worktree" in
+  help)
+    __help
+    ;;
+  list)
+    shift "$1"
+    worktree_option="${1:-}"
+    case "$worktree_option" in
+      -b)
+        git branch -r
+        ;;
+      *)
+        git worktree list --porcelain
+        ;;
+    esac
+    ;;
+  -)
+    echo "in -"
+    directory=$(git worktree list --porcelain | grep -E 'worktree ' | awk '{print $0; exit}' | cut -d ' ' -f2-)
+    ;;
+  \?)
+    # NOTE: this covers the case where an optarg may not be provided
+    # and will exit errored
+    echo "No argument given" 1>&2
+    exit 1
+    ;;
+    # *)
+    #   directory=$(git worktree list --porcelain | grep -E 'worktree ' | awk '/'"$worktree"'/ {print; exit}' | cut -d ' ' -f2- | fzf)
+    #   ;;
+esac
+# echo "directory: $directory"
 # If directory variable is not empty then change worktree
 if [[ "$directory" == "" ]]; then
-  git worktree list
+  worktrees="$(git worktree list --porcelain | grep -E 'worktree ' | awk '/'"$worktree"'/ {print;}' | cut -d ' ' -f2-)"
+  if [[ "$worktrees" -gt "1" ]]; then
+    __change_worktree "$("$worktrees" | fzf)"
+  else
+    # git worktree list && __help
+    __help
+  fi
 else
   __change_worktree "$directory"
 fi
