fix(nvim): move bootstrapping higher up

diff --git a/bin/paq-install b/bin/paq-install
--- a/bin/paq-install
+++ b/bin/paq-install
@@ -19,17 +19,37 @@ __root="$(cd "$(dirname "${__dir}")" && pwd)"
 # shellcheck disable=SC2034,SC2015
 __invocation="$(printf %q "${__file}")$( (($#)) && printf ' %q' "$@" || true)"
 
+FORCE_INSTALL="false"
+
 paq_path="${XDG_DATA_HOME}/nvim/site/pack/paqs/start/paq-nvim"
 
 do_install() {
   log "cloning paq-nvim into $paq_path"
-  git clone --depth=1 https://github.com/savq/paq-nvim.git $paq_path \
-    && nvim -c 'lua require("paq")(require("plugins").list):install()' +qall \
+  git clone --depth=1 https://github.com/savq/paq-nvim.git "$paq_path" \
+    && nvim --headless -u NONE -c 'lua require("plugins").bootstrap()' \
     && log_ok "completed installing paq-nvim and plugins into $paq_path" \
     || exit 1
 }
 
-if [[ ! -d $paq_path ]]; then
+while getopts "f" OPTION; do
+  case $OPTION in
+
+    f)
+      FORCE_INSTALL="true"
+      ;;
+
+    \?)
+      echo "Invalid Option: -$OPTARG" 1>&2
+      exit 1
+      ;;
+
+  esac
+done
+shift $((OPTIND - 1))
+
+if [[ -d $paq_path && $FORCE_INSTALL == "false" ]]; then
+  log_warn "paq-nvim already exists at $paq_path; skipping."
+else
   read -p "$(tput bold)$(tput setaf 5)[?] install paq-nvim and plugins (Y/n)?$(tput sgr 0) " yn
   case $yn in
     [Yy]*)
@@ -46,6 +66,4 @@ if [[ ! -d $paq_path ]]; then
       exec $__invocation
       ;;
   esac
-else
-  log_warn "paq-nvim already exists at $paq_path; skipping."
 fi
