yuge..

diff --git a/bin/preview b/bin/preview
--- a/bin/preview
+++ b/bin/preview
@@ -1,261 +1,240 @@
 #!/usr/bin/env bash
 
-FILE_PATH="${1}" # Full path of the highlighted file
-WIDTH="${2}"     # Width of the preview pane (number of fitting characters)
-HEIGHT="${3}"    # Height of the preview pane (number of fitting characters)
-X="${4}"         # X coordinate of the preview pane
-Y="${5}"         # Y coordinate of the preview pane
+source "${HOME}/.dotfiles/config/zsh/lib/helpers.zsh"
 
-if ! [ -f "$FILE_PATH" ] && ! [ -h "$FILE_PATH" ]; then
-  exit
-fi
+# Add this script to $PATH. Then use this by: fzf --preview='preview {}'.
+# Requirements:
+# - chafa for image
+# - jq for json
+# - exa for directory
+# - elinks for html
+# - glow for markdown
+# - transmission-show for torrent
+# - bat for text files
+# - atool for viewing zips
+# - exiftool for videos and gifs
+# - readelf for viewing binaries
 
-FILE_EXTENSION="${FILE_PATH##*.}"
-FILE_EXTENSION_LOWER="$(printf "%s" "$FILE_EXTENSION" | tr '[:upper:]' '[:lower:]')"
-MIME_TYPE="$(file --dereference --brief --mime-type -- "$FILE_PATH")"
+[ "$1" = "" ] && exit 1
 
-# [ -n "$WIDTH" ] && [ -n "$HEIGHT" ] && [ -n "$X" ] && [ -n "$Y" ] || PAGE_MODE=$?
-[ $# -gt 1 ] || PAGE_MODE=$?
+DEBUG_LOG="/tmp/fzf_preview_fifo_debug.log"
+UEBERZUGPP_FIFO="/tmp/fzf_preview_fifo"
+ID="preview-ueberzugpp"
+WIDTH="$FZF_PREVIEW_COLUMNS"
+HEIGHT="$FZF_PREVIEW_LINES"
 
-hash() {
-  printf '%s/.cache/lf/%s.jpg' "$HOME" \
-    "$(gstat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | md5 -q | awk '{print $1}')"
+# fzf changes its preview paddings several times, its confusing
+VPAD=$(fzf --version | {
+  IFS='. ' read -r v1 v2 _
+  [ "$v1" = 0 ] && [ "$v2" -le 26 ] && echo 0 || echo 4
+})
+
+[ -p "$UEBERZUGPP_FIFO" ] || mkfifo "$UEBERZUGPP_FIFO"
+
+cleanup() {
+  # log_info "cleaning up.."
+  if [ "$1" != "0" ]; then
+    log_error "FATAL error code \"${1}\" occurred on line \"${2}\""
+  fi
+
+  pkill ueberzugpp
+  test -p "$UEBERZUGPP_FIFO" && rm -f "$UEBERZUGPP_FIFO"
+  rm /tmp/ueberuzgpp-* 2>/dev/null
+  rm /tmp/fzf_preview-* 2>/dev/null
+}
+#
+# clean_exit() {
+#   # cleanup
+#   set +x
+#   if [ $1 != "0" ]; then
+#     log_error "FATAL error code \"${1}\" occurred on line \"${2}\""
+#   fi
+# }
+#
+# trap 'cleanup $? $LINENO' EXIT INT QUIT
+trap 'cleanup $? $LINENO' EXIT INT QUIT
+# trap cleanup EXIT INT QUIT
+
+start_preview() {
+  # echo '{"path": "'"$1"'", "action": "add", "identifier": "fzfpreview", "x": 100, "y": 5, "width": 100, "height": 20}' >"$UEBERZUGPP_FIFO"
+  # echo "$1"
+  # export UEBERZUGPP_FIFO="$UEBERZUGPP_FIFO"
+  # rm -f "$UEBERZUGPP_FIFO"
+  # mkfifo "$UEBERZUGPP_FIFO"
+
+  {
+    printf '{ "action": "add", "identifier": "%s", "path": "%s",' "$ID" "$1"
+    # printf '"x": %d, "y": %d,' 2 1
+    printf '"x": %d, "y": %d, "scaler": "fit_contain",' 2 1
+    printf '"max-width": %d, "max-height": %d,' "$((WIDTH - VPAD))" "$((HEIGHT - 2))"
+    # printf '"max-width": %d, "max-height": %d }\n' "$((WIDTH - VPAD))" "$((HEIGHT - 2))"
+    printf '"width": %d, "height": %d }\n' "100" "$((HEIGHT - 2))"
+  } >"$UEBERZUGPP_FIFO" 2>"$DEBUG_LOG" ||
+    printf '{ "action": "remove", "identifier": "%s" }\n' "$ID" >"$UEBERZUGPP_FIFO" 2>"$DEBUG_LOG"
+
+  exec 3>"$UEBERZUGPP_FIFO"
 }
 
-IMAGE_CACHE_PATH="$(hash "$FILE_PATH")" # Full path that should be used to cache image preview
+stop_preview() {
+  printf '{ "action": "remove", "identifier": "%s" }\n' "$ID" >"$UEBERZUGPP_FIFO" 2>"$DEBUG_LOG"
+  exec 3>&-
+}
 
 handle_image() {
-  ##**********************************************************************
-  ## adopted from ranger scope.sh
-  ## replace exit with return
-  ##**********************************************************************
-
-  ## Size of the preview if there are multiple options or it has to be
-  ## rendered from vector graphics. If the conversion program allows
-  ## specifying only one dimension while keeping the aspect ratio, the width
-  ## will be used.
-  local DEFAULT_SIZE
-  DEFAULT_SIZE=$(kitty +kitten icat --print-window-size)
-  if [ "$DEFAULT_SIZE" = "" ]; then
-    DEFAULT_SIZE="1024x768"
-  fi
-
-  case "$MIME_TYPE" in
-      ## SVG
-    image/svg+xml | image/svg)
-      rsvg-convert --keep-aspect-ratio --width "${DEFAULT_SIZE%x*}" "$FILE_PATH" -o "${IMAGE_CACHE_PATH}.png" &&
-      mv "${IMAGE_CACHE_PATH}.png" "$IMAGE_CACHE_PATH" &&
-      return 6
-      return 1
-      ;;
-
-      ## DjVu
-      # image/vnd.djvu)
-      #     ddjvu -format=tiff -quality=90 -page=1 -size="${DEFAULT_SIZE}" \
-        #           - "${IMAGE_CACHE_PATH}" < "${FILE_PATH}" \
-        #           && return 6 || return 1 ;;
-
-      ## Image
+  case "$1" in
     image/*)
-      local orientation
-      orientation="$(identify -format '%[EXIF:Orientation]\n' -- "$FILE_PATH")"
-      ## If orientation data is present and the image actually
-      ## needs rotating ("1" means no rotation)...
-      if [[ -n "$orientation" && "$orientation" != 1 ]]; then
-        ## ...auto-rotate the image according to the EXIF data.
-        convert -- "$FILE_PATH" -auto-orient "$IMAGE_CACHE_PATH" && return 6
-      fi
-
-      ## `w3mimgdisplay` will be called for all images (unless overridden
-      ## as above), but might fail for unsupported types.
-      return 7
-      ;;
-
-      ## Video
-    video/*)
-      # Get embedded thumbnail
-      ffmpeg -i "$FILE_PATH" -map 0:v -map -0:V -c copy "$IMAGE_CACHE_PATH" && return 6
-      # Get frame 10% into video
-      ffmpegthumbnailer -i "$FILE_PATH" -o "$IMAGE_CACHE_PATH" -s 0 && return 6
-      return 1
-      ;;
-
-      ## Audio
-    audio/*)
-      # Get embedded thumbnail
-      ffmpeg -i "$FILE_PATH" -map 0:v -map -0:V -c copy \
-        "$IMAGE_CACHE_PATH" && return 6
-      ;;
-
-      ## PDF
-    application/pdf)
-      pdftoppm -f 1 -l 1 \
-        -scale-to-x "${DEFAULT_SIZE%x*}" \
-        -scale-to-y -1 \
-        -singlefile \
-        -jpeg -tiffcompression jpeg \
-        -- "$FILE_PATH" "${IMAGE_CACHE_PATH%.*}" &&
-      return 6 || return 1
-      ;;
-
-      ## ePub, MOBI, FB2 (using Calibre)
-      # application/epub+zip|application/x-mobipocket-ebook|\
-        # application/x-fictionbook+xml)
-      #     # ePub (using https://github.com/marianosimone/epub-thumbnailer)
-      #     epub-thumbnailer "${FILE_PATH}" "${IMAGE_CACHE_PATH}" \
-        #         "${DEFAULT_SIZE%x*}" && return 6
-      #     ebook-meta --get-cover="${IMAGE_CACHE_PATH}" -- "${FILE_PATH}" \
-        #         >/dev/null && return 6
-      #     return 1 ;;
-
-      ## Font
-    application/font* | application/*opentype)
-      preview_png="/tmp/$(basename "${IMAGE_CACHE_PATH%.*}").png"
-      if fontimage -o "$preview_png" \
-        --pixelsize "120" \
-        --fontname \
-        --pixelsize "80" \
-        --text "  ABCDEFGHIJKLMNOPQRSTUVWXYZ  " \
-        --text "  abcdefghijklmnopqrstuvwxyz  " \
-        --text "  0123456789.:,;(*!?') ff fl fi ffi ffl  " \
-        --text "  The quick brown fox jumps over the lazy dog.  " \
-        "$FILE_PATH"; then
-        convert -- "$preview_png" "$IMAGE_CACHE_PATH" &&
-        rm "$preview_png" &&
-        return 6
-      else
-        return 1
-      fi
-      ;;
-
-      ## Preview archives using the first image inside.
-      ## (Very useful for comic book collections for example.)
-      # application/zip|application/x-rar|application/x-7z-compressed|\
-        #     application/x-xz|application/x-bzip2|application/x-gzip|application/x-tar)
-      #     local fn=""; local fe=""
-      #     local zip=""; local rar=""; local tar=""; local bsd=""
-      #     case "${mimetype}" in
-      #         application/zip) zip=1 ;;
-      #         application/x-rar) rar=1 ;;
-      #         application/x-7z-compressed) ;;
-      #         *) tar=1 ;;
-      #     esac
-      #     { [ "$tar" ] && fn=$(tar --list --file "${FILE_PATH}"); } || \
-        #     { fn=$(bsdtar --list --file "${FILE_PATH}") && bsd=1 && tar=""; } || \
-        #     { [ "$rar" ] && fn=$(unrar lb -p- -- "${FILE_PATH}"); } || \
-        #     { [ "$zip" ] && fn=$(zipinfo -1 -- "${FILE_PATH}"); } || return
+      # TODO:
+      # https://github.com/justchokingaround/dotfiles/commit/4a1330f49d82c6fd687a96d3edc8fb9d20427e79
       #
-      #     fn=$(echo "$fn" | python -c "from __future__ import print_function; \
-        #             import sys; import mimetypes as m; \
-        #             [ print(l, end='') for l in sys.stdin if \
-        #               (m.guess_type(l[:-1])[0] or '').startswith('image/') ]" |\
-        #         sort -V | head -n 1)
-      #     [ "$fn" = "" ] && return
-      #     [ "$bsd" ] && fn=$(printf '%b' "$fn")
-      #
-      #     [ "$tar" ] && tar --extract --to-stdout \
-        #         --file "${FILE_PATH}" -- "$fn" > "${IMAGE_CACHE_PATH}" && return 6
-      #     fe=$(echo -n "$fn" | sed 's/[][*?\]/\\\0/g')
-      #     [ "$bsd" ] && bsdtar --extract --to-stdout \
-        #         --file "${FILE_PATH}" -- "$fe" > "${IMAGE_CACHE_PATH}" && return 6
-      #     [ "$bsd" ] || [ "$tar" ] && rm -- "${IMAGE_CACHE_PATH}"
-      #     [ "$rar" ] && unrar p -p- -inul -- "${FILE_PATH}" "$fn" > \
-        #         "${IMAGE_CACHE_PATH}" && return 6
-      #     [ "$zip" ] && unzip -pP "" -- "${FILE_PATH}" "$fe" > \
-        #         "${IMAGE_CACHE_PATH}" && return 6
-      #     [ "$rar" ] || [ "$zip" ] && rm -- "${IMAGE_CACHE_PATH}"
-      #     ;;
-  esac
-
-  # openscad_image() {
-  #     TMPPNG="$(mktemp -t XXXXXX.png)"
-  #     openscad --colorscheme="${OPENSCAD_COLORSCHEME}" \
-    #         --imgsize="${OPENSCAD_IMGSIZE/x/,}" \
-    #         -o "${TMPPNG}" "${1}"
-  #     mv "${TMPPNG}" "${IMAGE_CACHE_PATH}"
-  # }
-
-  case "$FILE_EXTENSION_LOWER" in
-      ## 3D models
-      ## OpenSCAD only supports png image output, and ${IMAGE_CACHE_PATH}
-      ## is hardcoded as jpeg. So we make a tempfile.png and just
-      ## move/rename it to jpg. This works because image libraries are
-      ## smart enough to handle it.
-      # csg|scad)
-      #     openscad_image "${FILE_PATH}" && return 6
-      #     ;;
-      # 3mf|amf|dxf|off|stl)
-      #     openscad_image <(echo "import(\"${FILE_PATH}\");") && return 6
-      #     ;;
-    drawio)
-      /Applications/draw.io.app/Contents/MacOS/draw.io -x "$FILE_PATH" -o "$IMAGE_CACHE_PATH" \
-        --width "${DEFAULT_SIZE%x*}" && return 6
-      return 1
+      # ueberzugpp layer --silent --parser json <"$UEBERZUGPP_FIFO" 2>"$DEBUG_LOG" &
+      # ueberzugpp layer -o kitty --no-cache --parser json <"$UEBERZUGPP_FIFO" 2>"$DEBUG_LOG" &
+      # ueberzugpp layer -o kitty --parser json <"$UEBERZUGPP_FIFO" 2>"$DEBUG_LOG" &
+      # ueberzugpp cmd -s "$UEBERZUGPP_FIFO" -i fzfpreview -a add -x "$X" -y 1 --max-width "$FZF_PREVIEW_COLUMNS" --max-height "$FZF_PREVIEW_LINES" -f "$2"
+      # start_preview "$2"
+      # sleep 1
+      chafa "$2"
       ;;
+    *) exiftool -All "$2" ;;
   esac
 }
 
-hold() {
-  tput civis >/dev/tty 2>/dev/null # hide cursor
-  read -n 1 -s -r
-  # stty raw
-  # dd bs=1 count=1 &>/dev/null
-  # stty cooked
-  tput cnorm >/dev/tty 2>/dev/null # show cursor
-}
-
-draw() {
-  if [ "$PAGE_MODE" ]; then
-    WIDTH=${lf_width:=$(tput cols)}
-    HEIGHT=${lf_height:=$(tput lines)}
-    X=0
-    Y=0
-  fi
-  if [ "$TMUX" != "" ]; then
-    WIDTH=$((WIDTH - 1))
-    HEIGHT=$((HEIGHT - 1))
-  fi
-  if [ "$PAGE_MODE" ]; then
-    clear
-    kitty +kitten icat --stdin no --transfer-mode memory --place "${WIDTH}x${HEIGHT}@${X}x${Y}" "$1" </dev/null >/dev/tty
-    hold
-    kitty +kitten icat --clear --stdin no --transfer-mode memory </dev/null >/dev/tty
-  else
-    # preview launched in preview mode
-    kitty +kitten icat --stdin no --transfer-mode memory --place "${WIDTH}x${HEIGHT}@${X}x${Y}" "$1" </dev/null >/dev/tty
-    exit 1 # needed for the preview to refresh
-  fi
-}
-
-fallback() {
-  echo "$FILE_PATH"
-  bat --color=always --style=header,grid --line-range :300 "$FILE_PATH"
-  # if [ "$PAGE_MODE" ]; then
-  #   pistol -c ~/.config/pistol/pistol.conf "$FILE_PATH" | less -R
-  # else
-  #   pistol -c ~/.config/pistol/pistol.conf "$FILE_PATH"
-  # fi
-}
-
-# check if cached file exists, if not, create it
-if [ -f "$IMAGE_CACHE_PATH" ]; then
-  image="$IMAGE_CACHE_PATH"
-else
-  handle_image "$FILE_PATH"
-  case $? in
-    0) ;;
-    1) ;;
-    2) ;;
-    3) ;;
-    4) ;;
-    5) ;;
-    6) image="$IMAGE_CACHE_PATH" ;;
-    7) image="$FILE_PATH" ;;
+handle_text() {
+  case "$2" in
+    *.md) glow --style=auto "$2" ;;
+    *.htm | *.html) elinks -dump "$2" ;;
+    *) bat --theme=base16 --color=always --paging=never --number --italic-text=never --tabs=2 --wrap=never "$2" ;;
   esac
-fi
+}
 
-if [ "$image" != "" ]; then
-  draw "$image"
-else
-  fallback
-fi
+mime="$(file --brief --mime-type "$1")"
+echo "$mime"
+case "$mime" in
+  text/*) handle_text "$mime" "$1" ;;
+  inode/directory) exa --long --icons --color=always "$1" ;;
+  inode/symlink) printf "Symbolic link to: \e[34m%s\e[0m." "$(readlink "$1")" ;;
+  application/json) jq --color-output <"$1" ;;
+  application/x-bittorrent) transmission-show --unsorted "$1" ;;
+  application/x-executable | application/x-pie-executable | application/x-sharedlib) readelf --wide --demangle=auto --all "$1" ;;
+  application/zip) atool --list "$1" ;;
+  image/* | video/*)
+    handle_image "$mime" "$1"
+    stop_preview
+    ;;
+  font/* | application/vnd.ms-opentype)
+    preview-font "$1"
+    ;;
+  *) exit 1 ;;
+esac
+
+# #!/usr/bin/env sh
+# #
+# # Source of inspiration: https://github.com/junegunn/fzf/issues/1928
+# # Was initially needed to not render `bat` errors into the preview window
+# #
+#
+# # set -eu
+# # IFS=$(printf '\n\t')
+# #
+# # INPUT="$1"
+# #
+# # if [ -d "$INPUT" ]; then
+# #   tree "$INPUT"
+# # elif [ -f "$INPUT" ]; then
+# #   case "$INPUT" in
+# #     # TODO: use https://github.com/jstkdng/ueberzugpp/blob/master/scripts/fzfub when ueberzugpp will be in the homebrew upstream
+# #     # More info: https://github.com/junegunn/fzf/issues/3228#issuecomment-1517845143
+# #     *".jpg" | *".jpeg" | *".png" | *".gif" | *".tiff")
+# #       ueberzugpp cmd -s "$UB_SOCKET" -a add -i PREVIEW -x "$X" -y "$Y" --max-width "$MW" --max-height "$MH" -f "$FILE_PATH"
+# #       ;;
+# #     # image "$INPUT" ;;
+# #     *".pdf" | *".djvu") zathura "$INPUT" ;;
+# #     *) bat --color=always --style numbers,changes "$INPUT" ;;
+# #   esac
+# # else
+# #   printf "%s" "$INPUT"
+# # fi
+#
+# check() {
+#   command -v "$1" >/dev/null 2>&1
+# }
+#
+# image() {
+#   FILE_PATH="$1"
+#   X=$4
+#   Y=$5
+#   MW=$(($2 - 1))
+#   MH=$3
+#   X=0
+#   Y=0
+#   MW=100
+#   MH=100
+#   # echo "$1 $2 $3 $4 $5"
+#   ueberzugpp cmd -s "$UB_SOCKET" -a add -i PREVIEW -x "$X" -y "$Y" --max-width "$MW" --max-height "$MH" -f "$FILE_PATH"
+#   exit 1
+# }
+#
+# fileordir() {
+#   [ -d "$1" ] && {
+#     check exa && exa -ahFT -L=1 --color=auto --icons --sort=size --group-directories-first "$1" || ls "$1"
+#     return
+#   }
+#   file="$1"
+#   shift
+#   check bat && bat --color=always --style=plain --pager=never "$file" "$@" || cat "$file"
+# }
+#
+# mkdir -p "$HOME/.cache/preview"
+# # CACHE="$HOME/.cache/preview/thumbnail.$(stat --printf "%n\0%i\0%F\0%s\0%W\0%Y" "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
+# CACHE="$HOME/.cache/preview/thumbnail.$(stat "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
+# # CACHE="$HOME/.cache/preview/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"
+#
+# echo ""
+# echo "$CACHE"
+# echo ""
+# echo "$(printf "%s\n" "$(readlink -f "$1")" | awk '{print tolower($0)}')"
+# echo ""
+#
+# case "$(printf "%s\n" "$(readlink -f "$1")" | awk '{print tolower($0)}')" in
+#   *.tgz | *.tar.gz) tar tzf "$1" ;;
+#   *.tar.bz2 | *.tbz2) tar tjf "$1" ;;
+#   *.tar.txz | *.txz) xz --list "$1" ;;
+#   *.tar) tar tf "$1" ;;
+#   *.zip | *.jar | *.war | *.ear | *.oxt) unzip -l "$1" ;;
+#   *.rar) unrar l "$1" ;;
+#   *.7z) 7z l "$1" ;;
+#   *.[1-8]) man "$1" | col -b ;;
+#   *.o) nm "$1" ;;
+#   *.torrent) transmission-show "$1" ;;
+#   *.iso) iso-info --no-header -l "$1" ;;
+#   *.odt | *.ods | *.odp | *.sxw) odt2txt "$1" ;;
+#   *.doc) catdoc "$1" ;;
+#   *.docx) docx2txt "$1" - ;;
+#   *.xls | *.xlsx)
+#     ssconvert --export-type=Gnumeric_stf:stf_csv "$1" "fd://1" | batorcat --language=csv
+#     ;;
+#   *.wav | *.mp3 | *.flac | *.m4a | *.wma | *.ape | *.ac3 | *.og[agx] | *.spx | *.opus | *.as[fx] | *.mka)
+#     exiftool "$1"
+#     ;;
+#   *.pdf)
+#     [ ! -f "${CACHE}.jpg" ] &&
+#       pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
+#     image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
+#     ;;
+#   *.avi | *.mp4 | *.wmv | *.dat | *.3gp | *.ogv | *.mkv | *.mpg | *.mpeg | *.vob | *.fl[icv] | *.m2v | *.mov | *.webm | *.ts | *.mts | *.m4v | *.r[am] | *.qt | *.divx)
+#     [ ! -f "${CACHE}.jpg" ] &&
+#       ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
+#     image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
+#     ;;
+#   *.bmp | *.jpg | *.jpeg | *.png | *.xpm | *.webp | *.gif | *.jfif)
+#     image "$1" "$2" "$3" "$4" "$5"
+#     ;;
+#   *.svg)
+#     [ ! -f "${CACHE}.jpg" ] &&
+#       convert "$1" "${CACHE}.jpg"
+#     image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
+#     ;;
+#   *)
+#     fileordir "$1"
+#     ;;
+# esac
+# exit 0
