[slack] adds dnd mode

diff --git a/bin/slack b/bin/slack
--- a/bin/slack
+++ b/bin/slack
@@ -20,75 +20,110 @@ help() {
   printf -- "Subcommands:\n"
   printf -- "    away               Set presence to away, and profile for being gone\n"
   printf -- "    lunch              Set presence to away, and profile for lunch\n"
-  printf -- "    pair               Set presence to away, and profile for pairing\n"
+  printf -- "    pair               Set DND to on, and profile for pairing\n"
+  printf -- "    dnd                Set DND to on, and profile for DND/focus\n"
   printf -- "    back               Set presence to auto, and profile accordingly\n"
   printf -- "\n"
 }
 
-function post_to_api () {
+function request() {
   # $1=token
   # $2=options
   # $3=endpoint
 
-  # hide curl output if we want, and send it to our spinner
-  # curl -s --data "" "https://slack.com/api/$3?token=$1&$2" | \
-  #   grep -q '"ok":true,' && \
-  #       echo "${green}Status updated ok${reset}" || \
-  #       echo "${red}There was a problem updating the status${reset}" | \
-  #   spinner
-  2>/dev/null 1>&2 curl -s -S --data "" "https://slack.com/api/$3?token=$1&$2" | spinner
+  # non-zero length string AND a value not equal to 0
+  # TODO: need better way to handle options/args that don't exist
+  if [[ -n $2 && $2 != 0 ]]; then
+    2>/dev/null 1>&2 curl -s -S --data "" "https://slack.com/api/$3?token=$1&$2" | spinner
+  else
+    2>/dev/null 1>&2 curl -s -S --data "" "https://slack.com/api/$3?token=$1" | spinner
+  fi
 }
 
-function post_profile () {
+function set_profile() {
   # $1=token
   # $2=options
-  post_to_api $1 $2 "users.profile.set"
+  request $1 $2 "users.profile.set"
 }
 
-function post_presence () {
+function set_presence() {
   # $1=token
   # $2=options
-  post_to_api $1 $2 "users.setPresence"
+  request $1 $2 "users.setPresence"
 }
 
-function post_all_presence () {
-  post_presence $ENBALA_TOKEN $1
-  post_presence $CIT_TOKEN $1
-  post_presence $MAGICCITYTECH_TOKEN $1
+function set_dnd() {
+  # $1=token
+  # $2=options
+  request $1 $2 "dnd.setSnooze"
 }
 
-function post_all_profile () {
-  post_profile $ENBALA_TOKEN $1
-  post_profile $CIT_TOKEN $1
-  post_profile $MAGICCITYTECH_TOKEN $1
+function end_dnd() {
+  # $1=token
+  # $2=options
+  request $1 $2 "dnd.endDnd"
 }
 
-function away () {
+
+function set_all_presence() {
+  set_presence $ENBALA_TOKEN $1
+  set_presence $CIT_TOKEN $1
+  set_presence $MAGICCITYTECH_TOKEN $1
+}
+
+function set_all_profile() {
+  set_profile $ENBALA_TOKEN $1
+  set_profile $CIT_TOKEN $1
+  set_profile $MAGICCITYTECH_TOKEN $1
+}
+
+function set_all_dnd() {
+  set_dnd $ENBALA_TOKEN $1
+  set_dnd $CIT_TOKEN $1
+  set_dnd $MAGICCITYTECH_TOKEN $1
+}
+
+function end_all_dnd() {
+  end_dnd $ENBALA_TOKEN $1
+  end_dnd $CIT_TOKEN $1
+  end_dnd $MAGICCITYTECH_TOKEN $1
+}
+
+function away() {
   presence="presence=away"
-  post_all_presence $presence
+  set_all_presence $presence
   profile="profile=%7B%22status_text%22:%22..adios..%22,%22status_emoji%22:%22:wave:%22%7D"
-  post_all_profile $profile
+  set_all_profile $profile
 }
 
-function lunch () {
+function lunch() {
   presence="presence=away"
-  post_all_presence $presence
+  set_all_presence $presence
   profile="profile=%7B%22status_text%22:%22..lunch..%22,%22status_emoji%22:%22:taco:%22%7D"
-  post_all_profile $profile
+  set_all_profile $profile
 }
 
-function pair () {
-  presence="presence=away"
-  post_all_presence $presence
+function pair() {
   profile="profile=%7B%22status_text%22:%22..pairing..%22,%22status_emoji%22:%22:pear:%22%7D"
-  post_all_profile $profile
+  set_all_profile $profile
+  dnd="num_minutes=120"
+  set_all_dnd $dnd
 }
 
-function back () {
-  presence="presence=auto"
-  post_all_presence $presence
+function dnd() {
+  profile="profile=%7B%22status_text%22:%22..working..%22,%22status_emoji%22:%22:octagonal_sign:%22%7D"
+  set_all_profile $profile
+  dnd="num_minutes=120"
+  set_all_dnd $dnd
+}
+
+function back() {
+  # presence="presence=auto"
+  # set_all_presence $presence
   profile="profile=%7B%22status_text%22:%22%22,%22status_emoji%22:%22%22%7D"
-  post_all_profile $profile
+  set_all_profile $profile
+  dnd=0
+  end_all_dnd $dnd
 }
 
 subcommand=$1
